{
 "title": "Requests Board",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Time in /api/sample",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Sample_Timer_seconds_max" }
   ]
  },
  {
   "title": "Time spend in Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "request_seconds_sum" }
   ]
  },
  {
   "title": "Maximum Requests Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "request_seconds_max" }
   ]
  }
 ]
}